name: KitChest
version: 1.2
main: KitChest\Main
author: QuiverlyRivalry
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10]
description: Kit Chest Plugin!
permissions:
 kit.give:
  default: op
 kit.test:
  default: op